# Generated by Django 5.2 on 2025-06-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binder", "0002_tagdictionary_review_reviewtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="tags",
        ),
        migrations.CreateModel(
            name="RecommendedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="binder.book"
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_books",
                        to="binder.recommendation",
                    ),
                ),
            ],
        ),
    ]
